// Mock data used when APIs are not connected yet

export const mockProfile = {
  id: "profile-1",
  name: "Rahul Kumar",
  email: "rahul.kumar@email.com",
  phone: "+91-9876543210",
  location: "Bangalore, India",
  titles: ["Full Stack Developer", "Software Engineer"],
  skills: ["Python", "React", "Node.js", "TypeScript", "PostgreSQL", "AWS", "Docker", "FastAPI"],
  experience_years: 4,
  experience: [
    {
      company: "Infosys",
      role: "Senior Software Engineer",
      duration: "2022 - Present",
      highlights: [
        "Built microservices architecture serving 1M+ daily requests",
        "Led migration from monolith to microservices reducing latency by 40%",
        "Mentored team of 4 junior developers",
      ],
    },
    {
      company: "TCS",
      role: "Software Engineer",
      duration: "2020 - 2022",
      highlights: [
        "Developed React dashboards for enterprise clients",
        "Implemented CI/CD pipelines reducing deployment time by 60%",
        "Created RESTful APIs with Node.js and Express",
      ],
    },
  ],
  education: [
    { degree: "B.Tech Computer Science", college: "VIT University", year: "2020" },
  ],
  certifications: ["AWS Solutions Architect Associate", "Meta React Developer"],
  summary:
    "Results-driven Full Stack Developer with 4+ years of experience building scalable web applications. Proficient in Python, React, and cloud technologies. Passionate about clean code and system design.",
};

export const mockJobs = [
  {
    id: "job-1",
    title: "Senior Full Stack Developer",
    company: "Grab",
    location: "Kuala Lumpur, Malaysia",
    remote_type: "Hybrid",
    salary_min: 8000,
    salary_max: 15000,
    salary_currency: "MYR",
    experience_level: "Mid-Senior",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    description:
      "We are looking for a Senior Full Stack Developer to join our engineering team. You will be responsible for building and maintaining scalable web applications...",
    apply_url: "https://grab.careers/job/12345",
    source: "Adzuna",
    posted_date: "2026-05-30",
    match_score: 92,
    recruiter_email: "hiring@grab.com",
  },
  {
    id: "job-2",
    title: "Python Backend Engineer",
    company: "Razorpay",
    location: "Bangalore, India",
    remote_type: "Remote",
    salary_min: 1800000,
    salary_max: 3000000,
    salary_currency: "INR",
    experience_level: "Mid",
    skills: ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker"],
    description:
      "Join our payments team to build highly reliable backend systems processing millions of transactions daily...",
    apply_url: "https://razorpay.com/careers/backend-eng",
    source: "RemoteOK",
    posted_date: "2026-05-29",
    match_score: 87,
    recruiter_email: null,
  },
  {
    id: "job-3",
    title: "Frontend Developer (React)",
    company: "Shopee",
    location: "Singapore",
    remote_type: "Onsite",
    salary_min: 6000,
    salary_max: 10000,
    salary_currency: "SGD",
    experience_level: "Mid",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "GraphQL"],
    description:
      "Build beautiful, performant user interfaces for our e-commerce platform serving millions of users across SEA...",
    apply_url: "https://careers.shopee.sg/job/fe-dev",
    source: "Adzuna",
    posted_date: "2026-05-28",
    match_score: 78,
    recruiter_email: "talent@shopee.sg",
  },
  {
    id: "job-4",
    title: "DevOps Engineer",
    company: "Flipkart",
    location: "Bangalore, India",
    remote_type: "Hybrid",
    salary_min: 2000000,
    salary_max: 3500000,
    salary_currency: "INR",
    experience_level: "Senior",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Python", "CI/CD"],
    description:
      "Lead our cloud infrastructure team. You'll design and implement scalable, fault-tolerant systems...",
    apply_url: "https://flipkart.com/careers/devops",
    source: "Remotive",
    posted_date: "2026-05-27",
    match_score: 65,
    recruiter_email: null,
  },
  {
    id: "job-5",
    title: "Full Stack Engineer",
    company: "Wise",
    location: "Remote (Global)",
    remote_type: "Remote",
    salary_min: 70000,
    salary_max: 110000,
    salary_currency: "USD",
    experience_level: "Mid-Senior",
    skills: ["React", "TypeScript", "Python", "PostgreSQL", "Microservices"],
    description:
      "Help us build the future of international money transfers. Work on complex financial systems with global scale...",
    apply_url: "https://wise.com/careers/fullstack",
    source: "RemoteOK",
    posted_date: "2026-05-30",
    match_score: 88,
    recruiter_email: "recruiting@wise.com",
  },
  {
    id: "job-6",
    title: "Software Engineer II",
    company: "Petronas Digital",
    location: "Kuala Lumpur, Malaysia",
    remote_type: "Onsite",
    salary_min: 7000,
    salary_max: 12000,
    salary_currency: "MYR",
    experience_level: "Mid",
    skills: ["Python", "React", "AWS", "Microservices", "PostgreSQL"],
    description:
      "Join our digital transformation team building internal tools and platforms for Malaysia's largest company...",
    apply_url: "https://petronasdigital.com/careers/swe2",
    source: "Adzuna",
    posted_date: "2026-05-26",
    match_score: 82,
    recruiter_email: "hr@petronasdigital.com",
  },
];

export const mockContacts = [
  {
    id: "contact-1",
    name: "Sarah Chen",
    email: "sarah.chen@grab.com",
    role: "Engineering Manager",
    company: "Grab",
    source: "Hunter.io",
    job_id: "job-1",
    contacted: false,
    replied: false,
  },
  {
    id: "contact-2",
    name: "Priya Sharma",
    email: "priya.sharma@razorpay.com",
    role: "Talent Acquisition Lead",
    company: "Razorpay",
    source: "Job Posting",
    job_id: "job-2",
    contacted: true,
    replied: false,
  },
  {
    id: "contact-3",
    name: "Ahmad Razali",
    email: "ahmad.r@petronasdigital.com",
    role: "HR Manager",
    company: "Petronas Digital",
    source: "Hunter.io",
    job_id: "job-6",
    contacted: true,
    replied: true,
  },
];

export const mockResume = {
  id: "resume-1",
  template: "modern",
  job_id: "job-1",
  sections: {
    summary:
      "Results-driven Full Stack Developer with 4+ years of experience specializing in React, Node.js, and cloud-native applications. Proven track record of building scalable systems serving 1M+ users, directly aligned with Grab's mission to deliver seamless digital experiences across Southeast Asia.",
    experience: [
      {
        company: "Infosys",
        role: "Senior Software Engineer",
        duration: "2022 - Present",
        bullets: [
          "Architected microservices platform handling 1M+ daily API requests with 99.9% uptime using Node.js and AWS",
          "Reduced system latency by 40% through strategic migration from monolith to distributed architecture",
          "Led cross-functional team of 4 engineers, implementing agile practices that improved sprint velocity by 25%",
        ],
      },
      {
        company: "TCS",
        role: "Software Engineer",
        duration: "2020 - 2022",
        bullets: [
          "Developed responsive React dashboards used by 500+ enterprise users, improving data accessibility by 60%",
          "Automated CI/CD pipelines with GitHub Actions, reducing deployment time from 2 hours to 15 minutes",
          "Built RESTful APIs serving 100K+ requests/day with Node.js, Express, and PostgreSQL",
        ],
      },
    ],
    skills: ["React", "TypeScript", "Node.js", "Python", "PostgreSQL", "AWS", "Docker", "FastAPI"],
    education: [
      { degree: "B.Tech Computer Science", college: "VIT University", year: "2020", gpa: "8.5/10" },
    ],
    certifications: ["AWS Solutions Architect Associate", "Meta React Developer"],
  },
  ats_score: 87,
};
